require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BladesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Blade. As you add validations to Blade, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BladesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all blades as @blades" do
      blade = Blade.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:blades)).to eq([blade])
    end
  end

  describe "GET #show" do
    it "assigns the requested blade as @blade" do
      blade = Blade.create! valid_attributes
      get :show, params: {id: blade.to_param}, session: valid_session
      expect(assigns(:blade)).to eq(blade)
    end
  end

  describe "GET #new" do
    it "assigns a new blade as @blade" do
      get :new, params: {}, session: valid_session
      expect(assigns(:blade)).to be_a_new(Blade)
    end
  end

  describe "GET #edit" do
    it "assigns the requested blade as @blade" do
      blade = Blade.create! valid_attributes
      get :edit, params: {id: blade.to_param}, session: valid_session
      expect(assigns(:blade)).to eq(blade)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Blade" do
        expect {
          post :create, params: {blade: valid_attributes}, session: valid_session
        }.to change(Blade, :count).by(1)
      end

      it "assigns a newly created blade as @blade" do
        post :create, params: {blade: valid_attributes}, session: valid_session
        expect(assigns(:blade)).to be_a(Blade)
        expect(assigns(:blade)).to be_persisted
      end

      it "redirects to the created blade" do
        post :create, params: {blade: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Blade.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved blade as @blade" do
        post :create, params: {blade: invalid_attributes}, session: valid_session
        expect(assigns(:blade)).to be_a_new(Blade)
      end

      it "re-renders the 'new' template" do
        post :create, params: {blade: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested blade" do
        blade = Blade.create! valid_attributes
        put :update, params: {id: blade.to_param, blade: new_attributes}, session: valid_session
        blade.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested blade as @blade" do
        blade = Blade.create! valid_attributes
        put :update, params: {id: blade.to_param, blade: valid_attributes}, session: valid_session
        expect(assigns(:blade)).to eq(blade)
      end

      it "redirects to the blade" do
        blade = Blade.create! valid_attributes
        put :update, params: {id: blade.to_param, blade: valid_attributes}, session: valid_session
        expect(response).to redirect_to(blade)
      end
    end

    context "with invalid params" do
      it "assigns the blade as @blade" do
        blade = Blade.create! valid_attributes
        put :update, params: {id: blade.to_param, blade: invalid_attributes}, session: valid_session
        expect(assigns(:blade)).to eq(blade)
      end

      it "re-renders the 'edit' template" do
        blade = Blade.create! valid_attributes
        put :update, params: {id: blade.to_param, blade: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested blade" do
      blade = Blade.create! valid_attributes
      expect {
        delete :destroy, params: {id: blade.to_param}, session: valid_session
      }.to change(Blade, :count).by(-1)
    end

    it "redirects to the blades list" do
      blade = Blade.create! valid_attributes
      delete :destroy, params: {id: blade.to_param}, session: valid_session
      expect(response).to redirect_to(blades_url)
    end
  end

end
